services:
  mysql_db:
    image: mysql:8.0.31-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pet_mate_db
    ports:
    - 3307:3306
  
  phpmyadmin:
    image: phpmyadmin:5.1.1
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - pet-mate

  pet-mate:
    container_name: pet-mate-container
    build: .
    volumes:
      - ./pet-mate-app:/var/www/html
    
